AWSTemplateFormatVersion: '2010-09-09'
Resources:

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: MANDEEP-KEY
      ImageId: ami-0d68d8cc09feec3b1
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-0b35aad6e0809e70a
          GroupSet:
            - sg-08bdfc852e142b299
      UserData: "CiMhL2Jpbi9iYXNoCnl1bSB1cGRhdGUgLXkKeXVtIGluc3RhbGwgLXkgaHR0cGQKd2dldCBodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vYWt1bGFzYXRoaXNoL2dpdG9wcy9tYWluL2luZGV4Lmh0bWwgLU8gL3Zhci93d3cvaHRtbC9pbmRleC5odG1sCnN5c3RlbWN0bCBzdGFydCBodHRwZApzeXN0ZW1jdGwgZW5hYmxlIGh0dHBkCg=="
      Tags:
        - Key: Name
          Value: SimpleHTMLApp

Outputs:
  EC2InstancePublicIP:
    Description: 'Public IP of the EC2 instance'
    Value: !GetAtt MyEC2Instance.PublicIp
  WebsiteURL:
    Value: !Sub 'http://${MyEC2Instance.PublicDnsName}'
    Description: 'URL to access the HTML app on EC2'
