AWSTemplateFormatVersion: '2010-09-09'
Resources:

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: MANDEEP-KEY
      ImageId: ami-0d68d8cc09feec3b1
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-0b35aad6e0809e70a
          GroupSet:
            - sg-08bdfc852e142b299
      UserData: |
        #!/bin/bash
        yum update -y
        yum install -y httpd
        # Fetching index.html from GitHub repository
        wget https://raw.githubusercontent.com/akulasathish/gitops/main/index.html -O /var/www/html/index.html
        systemctl start httpd
        systemctl enable httpd
      Tags:
        - Key: Name
          Value: SimpleHTMLApp

Outputs:
  EC2InstancePublicIP:
    Description: 'Public IP of the EC2 instance'
    Value: !GetAtt MyEC2Instance.PublicIp
  WebsiteURL:
    Value: !Sub 'http://${MyEC2Instance.PublicDnsName}'
    Description: 'URL to access the HTML app on EC2'
