AWSTemplateFormatVersion: '2010-09-09'
Resources:

  # EC2 Instance in your existing VPC and Subnet
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: MANDEEP-KEY  # Replace with your actual EC2 key pair name
      ImageId: ami-0d68d8cc09feec3b1  # Ensure this is a valid AMI for your region
      SecurityGroups:
        - Ref: MySecurityGroup
      SubnetId: subnet-0b35aad6e0809e70a  # Use your provided subnet ID
      NetworkInterfaces:
        - AssociatePublicIpAddress: true  # Ensure public IP is assigned
          DeviceIndex: '0'
      Tags:
        - Key: Name
          Value: SimpleHTMLApp

  # Security Group for the EC2 instance
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access on port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'

Outputs:
  EC2InstancePublicIP:
    Description: 'Public IP of the EC2 instance'
    Value: !GetAtt MyEC2Instance.PublicIp
  WebsiteURL:
    Value: !Sub 'http://${MyEC2Instance.PublicDnsName}'
    Description: 'URL to access the HTML app on EC2'
